version: "3.9"

services:
  apiserver:
    build:
      context: .
      target: dev
    image: kvdomingo/squadtime-api:latest
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/backend

  frontend:
    build:
      context: ./web/app
      target: dev
    image: kvdomingo/squadtime-web:latest
    env_file: ./web/app/.env
    volumes:
      - ./web/app:/frontend
