version: '3'

dotenv:
  - .env

env:
  PROD_NAME: squad-app-prod

tasks:
  default:
    cmds:
      - docker compose up -d --build

  sql-proxy:
    cmds:
      - cloud_sql_proxy -instances=$CLOUD_SQL_URL=tcp:0.0.0.0:3306

  logs:
    cmds:
      - docker compose logs --follow {{.CLI_ARGS}}

  shutdown:
    cmds:
      - docker compose stop {{.CLI_ARGS}}

  remove-all:
    cmds:
      - docker compose down -v --remove-orphans

  restart-proxy:
    cmds:
      - docker compose exec -- proxy nginx -s reload

  restart-all:
    cmds:
      - docker compose restart {{.CLI_ARGS}}

  prod:
    cmds:
      - docker compose -f docker-compose.prod.yml -p {{.PROD_NAME}} up -d --build

  prod-logs:
    cmds:
      - docker compose -f docker-compose.prod.yml -p {{.PROD_NAME}} logs --follow {{.CLI_ARGS}}

  prod-clean:
    cmds:
      - docker compose -f docker-compose.prod.yml -p {{.PROD_NAME}} down -v --remove-orphans