version: '3'

dotenv:
  - .env

env:
  NAME: squad-schedule-dev

tasks:
  default:
    cmds:
      - docker compose up -d --build {{.CLI_ARGS}}
      - task logs

  sqlproxy:
    cmds:
      - cloud_sql_proxy -instances=$CLOUD_SQL_URL=tcp:0.0.0.0:5555

  logs:
    cmds:
      - docker compose logs --follow {{.CLI_ARGS}}

  shutdown:
    cmds:
      - docker compose stop {{.CLI_ARGS}}

  remove-all:
    cmds:
      - docker compose down -v --remove-orphans

  reload-proxy:
    cmds:
      - docker compose exec -- proxy nginx -s reload

  restart:
    cmds:
      - docker compose restart {{.CLI_ARGS}}