version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - docker compose up -d --build

  sql-proxy:
    cmds:
      - cloud_sql_proxy -instances=$CLOUD_SQL_URL=tcp:0.0.0.0:3306

  logs:
    cmds:
      - docker compose logs --follow

  shutdown:
    cmds:
      - docker compose stop

  remove-all:
    cmds:
      - docker compose down -v --remove-orphans

  restart-proxy:
    cmds:
      - docker compose restart proxy

  restart-all:
    cmds:
      - docker compose restart
