version: '3'

tasks:
  default:
    cmds:
      - docker compose up -d --build

  logs:
    cmds:
      - docker compose logs --follow

  shutdown:
    cmds:
      - docker compose stop

  remove-all:
    cmds:
      - docker compose down -v --remove-orphans

  restart-proxy:
    cmds:
      - docker compose restart proxy

  restart-all:
    cmds:
      - docker compose restart
