# Generated by Django 3.2.4 on 2021-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_discorduser_discordid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discorduser",
            name="discriminator",
            field=models.CharField(max_length=4),
        ),
    ]
