# Generated by Django 4.0.4 on 2022-05-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', 'group', 'name']},
        ),
        migrations.DeleteModel(
            name='Bias',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
